"""
Pydantic models for transcript data.

Simplified transcript format using OpenAI's gpt-4o-transcribe model.
Returns plain text transcription without timestamps or speaker diarization.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class Transcript(BaseModel):
    """Plain text transcript without timestamps or speaker information.

    Generated by gpt-4o-transcribe model.
    """

    id: str = Field(..., description="Unique transcript identifier (8-char hex)")
    source: str = Field(..., description="YouTube URL or local file path")
    source_type: str = Field(..., description="'youtube' or 'local_file'")
    text: str = Field(..., description="Complete transcription text")
    duration: float = Field(..., description="Total audio duration in seconds")
    created_at: datetime = Field(
        ..., description="Timestamp when transcript was created"
    )
